[package]
name = "wasmnes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
console_error_panic_hook = "0.1.7"
console_log = "1.0.0"
js-sys = "0.3.72"
log = "0.4.22"
nes-core = {path = "../nes-core"}
wasm-bindgen = "0.2.95"
